// <auto-generated />
using DailyPlanner.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DailyPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260322150000_AddTodoistOAuthScopes")]
    partial class AddTodoistOAuthScopes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
