// <auto-generated />
using System;
using DailyPlanner.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DailyPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260320140000_AddCompletedDateToTaskInstances")]
    partial class AddCompletedDateToTaskInstances
    {
        // Note: BuildTargetModel is not required for applying migrations at runtime,
        // but EF tooling expects this method to exist on the generated designer.
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally minimal.
            // The authoritative model state is tracked by ApplicationDbContextModelSnapshot.
        }
    }
}

